### ISSUE TITLE
changes in "include Text" text box effect "highlight lines..." textbox

### ISSUE THREAD

**Issue by danw25** [philips-software/logviewer#74]
**Describe the bug**
changing the content of the include text text box will also change the text in the highlight lines

**To Reproduce**

1. write a  word in the include text
2. see it updated in the highlight textbox
3. write a different word
4. highlight textbox will change as well

see 

**Expected behavior**
highlight textbox stays the same unless directly altered
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LiorBanai** [comment]
this is works as specified as the user most likely wants to highlight the current filter criteria

**Comment by LiorBanai** [comment]
behavior changed: Highlight textbox is not connected to include texbox anymore
