### ISSUE TITLE
Accumulate all parsing errors and do not stop on first error

### ISSUE THREAD

**Issue by danw25** [philips-software/logviewer#9]
if a parse error is detected only the first error is shown.

desired behavior :
once a parsing error is found, continue from start of next line and report all errors

**Comment by LiorBanai** [comment]
this is implementation issue as each specific implementaion handles its own logic regarding parsing.
Analogy built in parser (for the Analogy Custom XML files) will be updated to handle corrupted log files but specific implementations should add its own logic to handle parsing errors

**Comment by LiorBanai** [comment]
not relevant for Analogy base code
